/** Starter OM 300 flashcards — edit or extend in the app; “Restore starter deck” resets to this list. */
export const SEED_FLASHCARDS = [
  { id: "om-def", front: "Operations management (core idea)", back: "Activities that create value by transforming inputs into outputs." },
  { id: "three-func", front: "Three essential business functions", back: "Marketing, Finance/Accounting, and Operations." },
  { id: "prod-sf", front: "Single-factor productivity", back: "Units produced ÷ labor hours used (or similar single input)." },
  { id: "prod-mf", front: "Multi-factor productivity", back: "Output ÷ (labor + materials + energy + capital + misc.)." },
  { id: "strat-om", front: "10 OM decision areas (examples)", back: "Design, quality, process/capacity, location, layout, HR/jobs, supply chain, inventory, scheduling, maintenance." },
  { id: "diff-cost-resp", front: "Three competitive strategies", back: "Differentiation, cost leadership, response (speed/flexibility/reliability)." },
  { id: "plc", front: "Product life cycle stages", back: "Introduction → growth → maturity → decline." },
  { id: "pm-phases", front: "Three project management phases", back: "Planning, scheduling, controlling." },
  { id: "cpm", front: "Critical path", back: "The longest path through the network; determines minimum project duration; activities on it have zero slack." },
  { id: "slack", front: "Slack time (two formulas)", back: "Slack = LS − ES, or Slack = LF − EF." },
  { id: "crash", front: "Project crashing", back: "Shorten duration by adding resources to critical activities; trade time vs cost—crash cheapest critical activity first." },
  { id: "forecast-naive", front: "Naïve forecast", back: "Next period forecast = last period’s actual demand." },
  { id: "forecast-ma", front: "Moving average", back: "Average of demand over the last n periods." },
  { id: "forecast-es", front: "Exponential smoothing", back: "Ft = Ft−1 + α(At−1 − Ft−1); higher α = more responsive." },
  { id: "mad", front: "MAD", back: "Mean absolute deviation: Σ|Actual − Forecast| ÷ n." },
  { id: "mape", front: "MAPE", back: "Mean absolute percent error—good for comparing across scales." },
  { id: "ts-components", front: "Four time-series components", back: "Trend, seasonality, cycles, random variation." },
  { id: "coq", front: "Four costs of quality", back: "Prevention, appraisal, internal failure, external failure." },
  { id: "six-sigma", front: "Six Sigma goal (defects)", back: "No more than 3.4 defects per million opportunities; DMAIC." },
  { id: "spc-assign", front: "Assignable vs common cause variation", back: "Assignable = specific identifiable cause (out of control). Common = natural random variation (in control)." },
  { id: "xbar-known", front: "X̄ chart limits when σ is known", back: "UCL/LCL = x̄̄ ± z·(σ ÷ √n)." },
  { id: "xbar-unknown", front: "X̄ chart when σ unknown", back: "Use R̄ and A₂: UCL/LCL = x̄̄ ± A₂R̄." },
  { id: "r-chart", front: "R chart", back: "Monitors within-sample variability; UCLᴿ = D₄R̄, LCLᴿ = D₃R̄." },
  { id: "p-chart", front: "p chart", back: "Fraction defective (attributes); limits use p̄ ± z·σ̂ₚ." },
  { id: "c-chart", front: "c chart", back: "Count of defects per unit; limits ≈ c̄ ± z√c̄." },
  { id: "proc-focus", front: "Four process strategies", back: "Process focus, repetitive focus, product focus, mass customization." },
  { id: "bottleneck", front: "Bottleneck", back: "Lowest-capacity operation that limits system throughput." },
  { id: "design-eff", front: "Design vs effective capacity", back: "Design = theoretical max; effective = realistic given constraints (≤ design)." },
  { id: "vertical-int", front: "Vertical integration", back: "Owning upstream (backward) or downstream (forward) operations for control vs capital trade-off." },
  { id: "bullwhip", front: "Bullwhip effect", back: "Small demand swings amplify upstream due to ordering behavior, batching, promotions, gaming." },
  { id: "inv-turn", front: "Inventory turnover", back: "COGS ÷ average inventory (higher = faster movement)." },
  { id: "abc", front: "ABC analysis", back: "Classify SKUs by annual $ volume—A items few SKUs, most value; tight control on A." },
  { id: "eoq", front: "EOQ purpose", back: "Economic order quantity balances ordering/setup cost vs holding cost to minimize total relevant cost." },
  { id: "eoq-form", front: "EOQ formula", back: "Q* = √(2DS ÷ H), where D = annual demand, S = order/setup cost, H = holding cost per unit per year." },
  { id: "rop", front: "Reorder point (basic)", back: "ROP = d × L (daily demand × lead time); add safety stock when variability matters." },
  { id: "epq", front: "EPQ vs EOQ", back: "EPQ applies when inventory arrives gradually (production rate p vs demand d); uses √(2DS/(H(1−d/p)))." },
  { id: "jit-lean", front: "JIT / Lean core idea", back: "Pull production, minimize waste and inventory; exposes problems so they must be fixed." },
  { id: "ohno-muda", front: "Ohno’s seven wastes", back: "Overproduction, waiting, transportation, inventory, motion, overprocessing, defects." },
  { id: "tps", front: "TPS two pillars", back: "Jidoka (stop for quality) and Just-in-Time (make what is needed when needed)." },
  { id: "kanban", front: "Kanban", back: "Signal-based pull control—downstream signals upstream for more material; limits WIP." },
];
